In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/files/Iceland_Stake_Data_Reprojected.csv')

In [3]:
df

,stake,yr,d1,d2,d3,lat,lon,elevation,rhow,rhos,bw_stratigraphic,bs_stratigraphic,ba_stratigraphic,bw_floating_date,bs_floating_date,ba_floating_date,RGIId,GLIMSId,Name
0,hn14aa,1995,17/09/1994,20/05/1995,16/09/1995,64.885013,-18.773871,1450.400000,NaN,NaN,2.07000,-1.43000,0.640,2.07000,-1.43000,0.6400,RGI60-06.00228,G341234E64913N,NaN
1,hn14aa,1996,16/09/1995,11/05/1996,03/10/1996,64.885013,-18.773871,1449.800000,NaN,NaN,1.83000,-1.30000,0.530,1.83000,-1.30000,0.5300,RGI60-06.00228,G341234E64913N,NaN
2,hn14aa,1999,04/10/1998,15/05/1999,23/09/1999,64.885013,-18.773871,1448.300000,NaN,NaN,NaN,NaN,1.040,NaN,NaN,1.0400,RGI60-06.00228,G341234E64913N,NaN
3,hn14aa,2000,23/09/1999,13/05/2000,23/09/2000,64.885013,-18.773871,1447.300000,513.0,600.0,2.49000,-1.11000,1.380,2.49000,-0.97000,1.5200,RGI60-06.00228,G341234E64913N,NaN
4,hn14aa,2001,23/09/2000,11/05/2001,28/09/2001,64.885013,-18.773871,1446.300000,499.0,600.0,1.63000,-0.84000,0.790,1.49000,-0.83000,0.6600,RGI60-06.00228,G341234E64913N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2889,Br7,2018,24/10/2017,09/05/2018,09/10/2018,64.369011,-16.282516,1248.982009,475.0,600.0,2.76700,-1.34000,1.427,2.65150,-1.08800,1.5635,RGI60-06.00483,G343523E64267N,Breidamerkurjoekull
2890,Br7,2019,09/10/2018,01/05/2019,18/10/2019,64.369418,-16.282116,1248.830000,547.0,600.0,2.12236,-1.94236,0.180,1.87036,-1.71486,0.1555,RGI60-06.00483,G343523E64267N,Breidamerkurjoekull
2891,Br7,2020,18/10/2019,05/05/2020,09/10/2020,64.368945,-16.282034,1247.130000,523.0,600.0,2.52000,-2.06400,0.456,2.29250,-1.81900,0.4735,RGI60-06.00483,G343523E64267N,Breidamerkurjoekull
2892,Br7,2021,09/10/2020,01/05/2021,15/10/2021,64.368874,-16.282383,1246.360000,5120.0,600.0,2.00000,-1.34600,0.654,1.75500,-1.08350,0.6715,RGI60-06.00483,G343523E64267N,Breidamerkurjoekull
2893,Br7,2022,15/10/2021,03/05/2022,17/10/2022,64.369078,-16.281955,1246.210000,510.0,600.0,2.67000,-1.21200,1.458,2.40750,-1.06500,1.3425,RGI60-06.00483,G343523E64267N,Breidamerkurjoekull

In [19]:
melted_df = pd.melt(df, id_vars=['stake','ba_stratigraphic', 'bw_stratigraphic', 'bs_stratigraphic'], value_vars=['d1', 'd2', 'd3'], var_name='Measurement Type', value_name='Measurement Date', ignore_index=True)

# Create separate DataFrames for each SMB type and corresponding date
winter_df = melted_df[melted_df['Measurement Type'] == 'd1'].copy()
winter_df['SMB'] = winter_df['bw_stratigraphic']
winter_df['Type'] = 'BW'

summer_df = melted_df[melted_df['Measurement Type'] == 'd2'].copy()
summer_df['SMB'] = summer_df['bs_stratigraphic']
summer_df['Type'] = 'BS'

annual_df = melted_df[melted_df['Measurement Type'] == 'd3'].copy()
annual_df['SMB'] = annual_df['ba_stratigraphic']
annual_df['Type'] = 'BA'

# Select only necessary columns
winter_df = winter_df[['Stake', 'Measurement Date', 'SMB', 'Type']]
summer_df = summer_df[['Stake', 'Measurement Date', 'SMB', 'Type']]
annual_df = annual_df[['Stake', 'Measurement Date', 'SMB', 'Type']]

# Concatenate the DataFrames
result_df = pd.concat([winter_df, summer_df, annual_df]).reset_index(drop=True)

KeyError: "['Stake'] not in index"