## Setting Up:

In [4]:
import pandas as pd
import os
import warnings
from tqdm.notebook import tqdm
import re
import massbalancemachine as mbm
import geopandas as gpd
from shapely.geometry import Polygon, LineString, Point

from scripts.helpers import *
from scripts.glamos_preprocess import *

warnings.filterwarnings('ignore')
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [15]:
df_pm = pd.read_csv(path_PMB_GLAMOS_csv + 'CH_wgms_dataset_topo.csv')
# Filter to start of MS data (1961):
df_pm = df_pm[df_pm.YEAR > 1960].sort_values(by = ['GLACIER', 'YEAR'], ascending = [True, True])

print('Number of winter and annual samples:', len(df_pm))
print('Number of annual samples:',
      len(df_pm[df_pm.PERIOD == 'annual']))
print('Number of winter samples:',
      len(df_pm[df_pm.PERIOD == 'winter']))
df_pm.head()

Number of winter and annual samples: 10918
Number of annual samples: 9063
Number of winter samples: 1855

,YEAR,POINT_ID,GLACIER,FROM_DATE,TO_DATE,POINT_LAT,POINT_LON,POINT_ELEVATION,POINT_BALANCE,PERIOD,RGIId,aspect,slope,dis_from_border,topo
5524,2006,100,adler,2005-10-17,2006-10-11,46.010637,7.855896,3096.507742,-2592,annual,RGI60-11.02764,NaN,NaN,NaN,NaN
5525,2006,200,adler,2005-10-17,2006-10-11,46.010052,7.858628,3141.506520,-2502,annual,RGI60-11.02764,NaN,NaN,NaN,NaN
5526,2006,300,adler,2005-10-17,2006-10-11,46.010646,7.860957,3191.502735,-2592,annual,RGI60-11.02764,NaN,NaN,NaN,NaN
5527,2007,100,adler,2006-10-11,2007-10-09,46.010602,7.855728,3093.507997,-2250,annual,RGI60-11.02764,NaN,NaN,NaN,NaN
5528,2007,200,adler,2006-10-11,2007-10-09,46.010169,7.858461,3124.506390,-1836,annual,RGI60-11.02764,NaN,NaN,NaN,NaN

In [26]:
# Get stakes per glacier
glStakes = {}
groupedByGL = df_pm.groupby(
    ['GLACIER', 'POINT_ID']).size().reset_index().sort_values(by=0,
                                                              ascending=False)
for gl in df_pm.GLACIER.unique():
    glStakes[gl] = groupedByGL[groupedByGL.GLACIER == gl].POINT_ID.unique()
glStakes

{'adler': array(['200', '400', '300', '600', '100', 's3-037', '600o', 'Ag-200',
        'Ag-400', 'Ag-600', 'FS193', 's3-256', '071', '059', '051', '038',
        '037', 'gpr1433', '200o', '079', 's3-25', 's4-23', 's4-32',
        's3-017', 's3-11', 's3-18', 's4-42'], dtype=object),
 'aletsch': array(['P3', 'P5', 'P9', 'P10', 'P11', 'PXX', 'EGIG', 'F', '76253', 'X',
        'G', '76353', 'AAA', 'P', '72254', 'AT', 'AR', 'BBB', '76454', 'J',
        'CCC', '77651', '76453', '72354', '77650', '6927', '75652',
        '72454', 'Z_61', 'R_64', 'AA', 'P9_59', 'W', 'T_61', 'DD', 'PP',
        'LL_69', 'G_64', 'EEE', 'CC', 'AV', 'Z', 'T', 'QQ_61', 'AS',
        '76452', 'R', '72253', 'V_61', 'Y_64', 'DDD', '6408', 'C', 'K',
        'AQ', 'W_61', 'U_61', '75651', '73650', '72453', '73653', 'J_57',
        '76352', 'H_IV', '72452', '73651', '73652', 'S_61', '6926',
        '75650', 'O_63', '73751', '77751', 'UU', 'V', 'D', 'SS', 'HH_69',
        '72252', '72251', 'Y', 'RR', 'P_64', 'V_69', 'C_67', 'AX', '75671',
        '76252', '76451', '72353', 'H', '75672', 'O', 'P3_60', 'U',
        'KK_69', 'Q', '72552', 'QQ', 'KK', 'T_69', '7116', '7107', 'OO_65',
        'E', 'EE', 'K_IV', 'L', 'M', '75670', '75751', '75752', '75850',
        '75851', '76450', '76250', '76251', 'D_67', '72352', '76350',
        '76351', '7109', '6921', '6922', '6923', '6924', '6925', 'P3F',
        '77750', '77851', 'U_69', 'VV', 'Z_69', 'RRR_III_71', 'P9_63',
        'NN', 'S', 'Q_63', 'S_III', 'TT', '20PN', 'L_67', 'L_71', 'AA_69',
        'AY', '6904', '6918', '6906', '02PN', '18P3', '07P3', '04P3',
        '04PN', '05P3', '05PN', '7117', '7105', '7106', 'Q_69',
        'RR_III_71', 'R_III_71', '72553', 'YY', 'ZZ', 'P9_61', 'N_63',
        'S_V', 'M_IV_69', 'M_I_69', 'M_VI_69', 'M_V_69', 'W_69', 'XX',
        '19PN', '2021', '20P3', '73852', 'J_71', '77850', 'HH_III_69',
        'HH_II_69', 'H_III_69', 'AZ', '97PN', '98PN', 'A', 'J_67', '77691',
        'FF', 'GG', 'H_II_69', '920', '75750', 'AU', 'BB', '79750',
        '79751', '95PN', '96PN', '79960', '79961', '83451', '83651',
        '72451', '79551', '79552', '79553', '79554', 'P3_61', 'OO',
        'M_II_69', 'M_IV', 'E_63', 'MM_III_69', 'MM_II_69', 'M_III_69',
        '72351', '72450', '75960', '75961', '77671', '77690', '77670',
        'S_69', '7108', 'P10_59', 'P10_64', 'JJ', 'P3_62', 'H_I_69',
        'H_VI_69', 'H_V_69', 'P5_62', '72554', '73750', '73851', '73960',
        '73961', '7112', '7113', '7114', '7115', '7118', '2419', '18PN',
        '19P3', '7110', '7111', 'XXX', 'VV_65', '12PN', '13P3', '14PN',
        '15PN', '16P3', '16PN', '17P3', '08PN', '09P3', '09PN', '17PN',
        '11', '11P3', '11PN', '12P3', '01PN', '00PN', '13PN', '14P3',
        '07PN', '08P3', '21PN', '2719', '10P3', '10PN', '03PN', '77960',
        '77961', 'CC_69', '79850', '79851', '02', '320', '38', '6902',
        '6903', '2421', '2422', '2619', '2721', '06', '06PN', 'XX_65',
        'YY_65', 'ZZ_65', 'WW', 'N', 'NN_69', 'S_IV', 'S_4', 'P5_65',
        's-08', 'P5_63', 'P13', 'N_67', 'O_69', 'K_III_69', 'K_II_69',
        'H_IV_68', 'H_V', 'P3_63', 'P3_64', 'P3_65', 'P5_61', 'K_V_69',
        'K_67', '99PN', 'HH_V_68', 'H_69', 'H_I', 'H_III', 'H_II_68',
        'EE_67', 'E_69', 'MM', 'M_67', 'K_I_69', 'K_VI_69', '7633',
        '84251', '84450', '84451', '84650', '922', '83450', '83650',
        '77860', 'C_63', 'DD_67', 'D_63', 'A_69', 'B', 'B_69', '7632',
        'HH_III_68', 'HH_II_68', 'HH_IV', 'HH_IV_68', 'HH_I_68', 'FF_67',
        'GG_67', '7538', '73690', '73691', '73951', '72551', '7101',
        '73952', '7532b', '83850', '84250', '7636', '7637', '7102', '7103',
        '7104', '22PN', '2120', '2121', '7119', '7120', '72250', '2722',
        '2919', '2920', '2122', '21P3', '2221', '2222', '22P3', '15P3',
        '10'], dtype=object),
 'allalin': array(['102', '104', '101', '103', '105', 'AVII', '106', '100', 'AV',
        'AVI', 'AIII', 'AXXI', 'AXXIII', 'AIV', 'AII', 'D', 'C', 'B', 'E',
        'A', '20106', 's-102', 's-104', '19101', '19102', '19103', '19104',
        '19105', '21100', '18106', '19100', '22100', '22101', '22102',
        '20100', '20101', '20102', '20103', '20104', '22104', '22105',
        '22106', '21101', '21102', '21103', '21104', '21105', '22103',
        '20105'], dtype=object),
 'arolla': array(['C06', 'C05', 'C03', 'C07', 'C08', 'C09', 'C10', 'C12', 'C16',
        'C18', 'C01', 'C02', 'C14', 'C15', 'y95', 'y96', 'y97', 'y98',
        'y99', 'y103', 'y93', 'y94', 'C11', 'y100', 'y101', 'y102'],
       dtype=object),
 'basodino': array(['11', '9', '10', '8', '2', '5', '4', '6', '12', '3', '1', '15',
        '14', '7', 'snl1', '01', '16', '09', '05', '02', '06', '04', '07',
        '03', 'snl2', 'snl3', '08', '2004', '2005', '2007', '2008', '2009',
        '2010', '2012', 'A020', '2003', 'B040', 'B041', 'B042', 'B043',
        'B044', 'B045', 'B054', '1712', '1801', 'bas10', 'bas5', 'bas8',
        's2-22', 's2-34', 'A023', '1808', '1809', '1705', '1706', '1707',
        '1708', '1709', '1710', '068', '1806', '1807', '1903', '1904',
        '1905', '1906', '1802', '1803', '1804', '1805', '1910', '1912',
        '2001', '2002', '1810', '1812', '1901', '1902', '010', '1907',
        '1908', '1909', '1703', '1704', '090', '104', '020', '028', '040',
        '1701', '1702'], dtype=object),
 'blauschnee': array(['BS3.7', '212', '3.6', 'BS7.2', 'BS3.6', 'BS4', 'BS7.1', '112',
        '312', '7.1', 'BS4.1', 'BS7', 'BS1/BS3.1', 'BS3.1', 'BS3.1-3',
        'BS7.1/BS7.2', 's1', 's2', 's3', 's4', 'BS3.1/BS3.3',
        'BS3.3/BS3.5', 'BS3.5/BS3.6'], dtype=object),
 'chessjen': array(['KI', 'KII'], dtype=object),
 'claridenL': array(['L'], dtype=object),
 'claridenU': array(['U'], dtype=object),
 'corbassiere': array(['B1', 'A3', 'B2', 'A1', 'B3', 'A2', 'R', '621', '623', '725',
        '625', '670', '723', '19725', '721', '722', '19625', '19670',
        '13670', '13722', '13723', '13725', '22625', '22673', '22675',
        '21721', '22621', '22623', '17723', '18621', '18623', '18625',
        '10723', '10725', '08723', '08725', '09621', '09623', '09625',
        '09670', '20673', '18670', '18721', '18723', '18725', '19621',
        '19623', '21673', '21675', '19721', '19723', '20621', '20623',
        '20625', '20670', '09721', '09723', '20675', '20721', '20723',
        '21623', '21625', '21670', '10623', '10625', '10670', '10721',
        '11625', '11670', '11721', '11723', '11725', '12621', '09725',
        '10621', '12670', '12723', '12725', '13621', '13623', '13625',
        '11621', '11623', '12623', '12625', '08623', '08625', '08670',
        '08721', '08621'], dtype=object),
 'corvatsch': array(['812', '212', '412', '712', '1013', '912', 's3', '612', 's2',
        '112', '217', '312', 's1', 's26', '417', '418', '512', '618',
        's11', 's16', 's7', 's8', 'nn', 's10', '11', '20', '27', '416',
        '1018'], dtype=object),
 'damma': array(['1200'], dtype=object),
 'diavolezza': array(['1'], dtype=object),
 'findelen': array(['700', '1010', '500', '800', '400', '200', '910', '810', '310',
        '820', '320', '940', '1020', '610', '120', '110', '300', '930',
        's309', '1140', 't2-66', 't3-12', 't3-20', 't3-23', 's4-623',
        's4-69', 't1-11', 't1-149', 't3-35', 't3-7', 'gpr1159', 'gpr1458',
        'gpr564', 'gpr95', 's119', 's2-01', 'gpr-167', 'gpr-322', 'gpr05',
        'gpr1', 's1-16', 's1-54', 's1-61', 's1-75', 's1-89', 's2-2',
        's2-23', 's2-46', 's3-053', 's3-077', 's3-122', 's3-310', 's1-122',
        's3-54', 's3-57', 's3-87', 's4-121', 's4-138', 's4-17', 's4-51',
        's2-123', '116', 'Fi-300', 'Fi-400', 'Fi-500', '500o', '800o',
        'Fi-810', 'Fi-820', 'Fi-910', 'Fi-930', 'Fi-940', 'WGMS',
        'Fi-1010', 'Fi-1020', 'Fi-700', 'Fi-800', '003', '037', '040',
        '066', '077', '084', '098', '100', '103'], dtype=object),
 'gietro': array(['4', '1', '2', '5', '8', '10', '6', '7', '9', '3', '103', '102',
        '104', '101', '106', '105', '107', '1901', '1702', '1904', '2002',
        '2005', '20101', '20102', '20107', '2104', '2105', '21101',
        '22101', '22107', '21102', '21107', '2201', '2202', '2204', '2205',
        '19107', '1701', '1704', '1805', '18102', '18107', '1905', '19101',
        '19102'], dtype=object),
 'gorner': array(['st35', 'st34', 'st42', 'st43', 'st14', 'st15', 'st45', 'st46',
        'st62', 'st63', 'st64', '0322', '0312', '0321', '0433', '0434',
        '0435', '0436', '0414', '0421', '0422', '0423', '0424', '0425',
        '0431', '0432', '0426', '0427', '0341', '0344', '0346', '0441',
        '0442', '0333', 'st24', '0443', '0444', '0445', '0446', 'st25',
        'st26', 'st31', 'st33', 'st41', '0347', '0412', '0326', 'st36',
        'st13', 'st16', 'st22', '0447', 'st47', 'st52', 'st53', 'st54',
        'st23', '0624', '0641', '0647', 'stbh2', '0342', '0336', 'st37',
        'st38', 'st44', 'st32', '0654', '0327', '0331', '0332', '0334',
        '0335', 'stbh4', 'stbh5', '0343', '0345', '0324', '0325', '0314',
        '0316', '0318', '0323'], dtype=object),
 'gries': array(['111', '112', '113', 'B', 'E', 'F', 'H', 'D', '91', 'C', '101',
        '102', '81', 'G', '41', '61', 'P2', '31', '51', '82', 'P6', '22',
        '42', '92', 'P5', '21', '52', '71', 'P7', 'K', 'P10', 'P1', 'P3',
        'V', '17', 'J', 'A', 'P4', 'P8', 'P9', '32', 'OP', 'U', 'P21',
        'SV', 'NO', 'AA', 'N', 'O', 'W', 'S', 'P', 'XX', 'R', 'Al21',
        'Al22', 'Al25', 'T', 'P27', 'P15', 'I', 'P39', 'P23', 'P34', 'II',
        'P33', 'Z', 'X', 'Al23', 'P18', 'Q', 'P13', 'AB', 'Al6', 'P22',
        'P14', 'P42', 'P30', 'BIII', 'P16', 'BIV', 'Al24', 'L', 'xxx',
        'P25', '022', '091', 'P26', 'P20', 'Y', 'P43', 'P29', 'P28', 'Px4',
        '042', '052', 'Px1', 'Px2', 'Px6', '062', '023', '053', '033',
        '032', 'M', 'Px8', 'Px3', 'Px7', 'Px5', 'P32', 'BV', '073', 'P24',
        '092', 'IV', '043', '083', 'VI', 'III', '063', 'P12', 'P19', 'Px9',
        'P37', '103', 'P11', 'P41', 'P38', 'P31', 'BVI', '021', '093',
        '082', '041', '051', 'p14', 'so', 'su', '015', '031', '061', '105',
        '011', '044', 'gr113-22', 'gr31-22', 'gr41-22', 'gr61-22', '56',
        '60', '36', 'HF', 'gr101-22', 'gr102-22', 'gr111-22', 'gr112-22',
        'gr91-22', 'gr92-22', 's1-004', 's1-014', 's1-050', 's1-063',
        's1-112', 's2-030', 'gr71-22', 'gr81-22', 'gr82-22', '026', '027',
        '028', '034', '104', '107', '110', '081', '090', '054', '071',
        '010', '072', '046', '047', '62', '64', '48', '50', '54', '004',
        '005', '007', '035', '014', '016', '017', '024', '003', 'Px10'],
       dtype=object),
 'gurschen': array(['503', '603', '605', '703', '705'], dtype=object),
 'hohlaub': array(['HII', '110', 'HI', 'HXXI', '19110', '22115', 's-119', '19115',
        '20115', '21110', '21115', '22110'], dtype=object),
 'joeri': array(['J1.4', 'J2', 'J3', 'J2.1', 'J1-J2', 'J1.2', 'J3.4', 'J2.2',
        'J2.3', 'J2.4', 'J2.5', 'J3.1', 'J3.3', 'J3.5', 'J3.6', 'J2.6',
        'J2.7', 'J1.1', 'J1.3', 'J1.5', 'J1.6', 'J1.7'], dtype=object),
 'limmern': array(['Aii', 'N', 'G', 'BII', 'Cii', 'F', 'BIII', 'Bi', 'E', 'Dii', 'Ci',
        'H', 'M', 'D', 'Bii', 'BBi', 'GG', 'CiiS', 'FFO', 'BI', 'CB', 'EE',
        'FFU', 'CH', 'MMi', 'ET', 'CCN', 'TT', 'TTT', 'R', 'SS', 'Mi',
        'RR', 'ES', 'MMM', 'NN', 'V', 'T', 'CCS', 'DD', 'S', 'U', 'AA',
        'AD', 'MM', 'MD', 'FS', 'FN', 'QQ', 'VV', 'AM', 'BB', '3', '1',
        '2', 'Ai'], dtype=object),
 'misaun': array(['tel'], dtype=object),
 'morteratsch': array(['M54', 'M51', 'M62', 'M20', 'M56', 'M57', 'AWS', 'ebk', 'M12',
        '22', 'M11', 'M23', 'M26', '44', 'M25', 'M58', 'M61', 'M59', 'M13',
        'M14', 'M60'], dtype=object),
 'murtel': array(['713', '312', '717', '212', '112', '412', '613', '417', '419',
        '513', '618', '619', '05', '219', '38', '318', '319', '35', '12',
        '215', '24', '75', '80', 'mur-122', 'mur-222', 'mur-322', '51',
        '515', '64', '119', '120', '121', '14', '10', '115', '719', '16',
        '18', '21', '217', '218', '116', '117', '118', '221', '25', '27',
        '29', '30', '316', '47', '49', '317', '33', '36', '41', '642',
        '415', '418', '42', 'mur-622', 'mur-722', 's-08', 's-20', 's-39',
        's-49', 's-69', 's14', 's24', 's35', 's39', 's52', 'mur-422'],
       dtype=object),
 'oberaar': array(['02', 'OA2.5', 'OA2', 'OA4', '01', '03', 'OA11', 'OA12', 'OA3'],
       dtype=object),
 'orny': array(['BA'], dtype=object),
 'otemma': array(['620', '720', '920', 's78', '420', '820', '520', '220', '320',
        '1020', '120', 's89', 's95', 's2', 's3', 's4', 's84', '2', '3',
        '4', '10', 's157', 's132', 's149', 's42', 's5', 's54', 's59',
        's70', '9', 's109', 's118', 's166', '5', '6', '7', '8'],
       dtype=object),
 'pers': array(['tel', 'P32', 'P33', 'P22', 'P21', 'P24', 'P26', 'P34', '33',
        'P23', 'P35', 'P25', 'P26H', 'P38', '0419', 'P24L', 'P32V', 'P21S',
        'P22X', 'P27', 'P31', 'P39B', 'P33S', 'P36', 'P38C', 'P39', '0520',
        '003', '0119', '0220', 's-03', 's-036', 's-04', 's-082', 's-108',
        'P40A', 'P41A', 'cr1a', '0620', '0622', '0719', '0720', '0722',
        'ps-0722', 's-01', 's-02', '0820', '135', '19', '47', '57', '82',
        '0421', '0519', 'P28A', 'P21U', 'P24N', 'P39D', 'P32X', 'P32Z',
        'cr1b', 'ps-0222', 'ps-0422', 'ps-0522', 'ps-0622', 'P37', 'P38E',
        's-136', 's-130', 'P33W', 'P33X'], dtype=object),
 'petitplanneve': array(['1'], dtype=object),
 'pizol': array(['207', '211', '206', '915', 'PS', '308', '618', '108', '112',
        '117', '118', '217', '218', '22', '517', '511', '114', '617',
        '812', '312', '712', '519', '912', '611', '513', '514', '515',
        '411', '412', '413', '414', '415', '03', '09', '10', '106', '508',
        '509', '510', '209', '21', '107', '109', '110', '111', '115',
        '215', '222', '240', '27', '13', '18', '409', '410', '277', '408',
        '416', '417', '418', '315', '316', '33', '34', '39', '574', '601',
        '609', '610', '815', '615', '621', '710', '711', '518', '54',
        '558', 's213', 's254', 's268', '73', '810', '811', '813', '814',
        '307', '309', '31', '310', '311', '914', '917', 's113', 's277',
        's29', 's30', 's313', 's40', 's41', 's413', 's44', 's513', 's53',
        's64', 's72', 's9', 's96', 'sp', 'ss'], dtype=object),
 'plainemorte': array(['511', '6', '3', '311', '315', '4', '5', '1', '617', '111', '114',
        '117n', '410', '417', '515', '611', '614', '615', '517', '310',
        '110', '115', '116', '13', 'plm5-22', 'plm6-h22', 's-07', 's-09',
        's-40', 's-63', 's-72', 's-85', '209', '001', '003', '032', '046',
        '071', '095', '109', 'V1', 'plm1-22', 'plm3-22', 'plm4-22', '418',
        's1-190', 's1-201', 's1-3', 's113', 'sd-2', 'sd-34', 's009',
        's080', 's094', 's1-156', '314', '318', '39', 's2-12', 's2-25',
        's3-09', 'sd-16'], dtype=object),
 'planneve': array(['2', 'snl'], dtype=object),
 'plattalva': array(['P11', 'P', 'Ki', 'OO', 'BIV', 'K', 'PP', 'JJ', 'KK', 'WX', 'XX',
        'X', 'W', 'WW', 'Z', 'Y', 'XY', 'YY', '4', 'J'], dtype=object),
 'rhone': array(['NN', 'alt_L7', '01', '08', '07', '0702', '0704', 'C121', '1805',
        '1812', '1504', '1603', '12', '06', '0705', 'g150_06', 'A012',
        'A083', 'A031', 'A062', '2012', '23', '1804', '0707', '0708',
        '0709', '0710', '1004', '0906', '0907', '0908', '0909', '0910',
        '0911', '0921', '0602', '0923', '0924', '0932', '0933', '1001',
        '1002', '1003', '0604', '0605', '0606', '0607', '0608', '0609',
        '0610', '02', '0711', '0801', '0802', '0611', '0701', '0703',
        '0706', '0603', '116', '1102', '1103', '1104', '1105', '1106',
        '1107', '1108', '0811', '1110', '1111', '1123', '1124', '113',
        '1133', '114', '0905', '0803', '0804', '0805', '0806', '0807',
        '0808', '0809', '0922', '0822', '0823', '0824', '0901', '0902',
        '0903', '0904', '1406', '1303', '1304', '1305', '1306', '1307',
        '1308', '1309', '1021', '1312', '1323', '1401', '1402', '1403',
        '1404', '1405', '1101', '1005', '1006', '1007', '1008', '1009',
        '1010', '1011', '1109', '1022', '1023', '1024', '1032', '1033',
        '107', '110', '1510', '1512', '1523', '1601', '1602', '1605',
        '1606', '1502', '1607', '1608', '1609', '1610', '1623', '164',
        '1701', '1702', '1302', '1201', '1202', '1203', '1204', '1205',
        '1206', '1207', '1310', '1208', '1209', '1210', '1211', '1223',
        '124', '1301', '1823', '189', '1901', '1902', '1903', '1723',
        '1801', '1802', '1906', '1907', '1908', '1909', '1923', '2001',
        '1808', '1809', '1409', '1410', '1412', '1423', '144', '1501',
        '1904', '1905', '1503', '1505', '1506', '1507', '1508', '1509',
        '1407', '1408', '2202', '2203', '2023', '208', '2101', '2102',
        '2103', '2104', '2212', '2223', '2106', '2107', '2108', '2109',
        '2123', '2201', '1709', '1710', '1712', '2204', '2205', '2206',
        '2207', '2208', '1803', '1806', '1807', '1704', '1705', '1706',
        '1707', '1708', 'A022', 'A035', 'A041', 'A043', 'A046', 'A051',
        'A001', 'A006', 'B380', 'A052', 'A063', 'A064', 'A073', 'A080',
        'A089', 'A021', '2009', 'A098', 'A103', 'A163', 'B096', 'B216',
        'B339', 'B370', '2105', '2002', '2003', '2004', '2005', '2006',
        '2007', '2008', 'g114_05', 'g153_09', 'k01', 'C633', 'C763',
        'HF05', 'RS444', 'RS474', 'k05', 'k06', 'g017_01', 'g018_02',
        'g021_03', 'g112_06', 'A009', 'A010', 'A013', 'A018', 'A020',
        'k02', 'k03', 'k04', 'C109', 'C116', 'C126', 'C136', 'C139',
        'C146', 'C631', 'RS539'], dtype=object),
 'rosatsch': array(['tel'], dtype=object),
 'sanktanna': array(['1115', '112', '212', '312', '817', '217', '712', '612', '412',
        '219', '318', '418', '27', '316', '320', 's31', 's32', 's53',
        's69', '53', '815', 'Akk5', '717', '913', '115', '118', 'Akk4',
        '01', '02', '414', '915', '916', '917', 'Akk1', 'Akk2', '615',
        '715', '716', '11', 'Akk3', 's-09', 's-19', 's-36', 's110', 's121',
        '819', '120', '16', '19', '20', '216', '06', '1014', '1015', '415',
        '416', '417', '420', '23', '25', '315', '32', '814', '45', '46',
        '48', '813', 's132', 's134', 's26', 's27', 's35', 's36', 's38',
        's4', 's124', 's125', 's126', 's129', 's77', 'sta-122', 'sta-222',
        'sta-322', 's29', 's30', '50', '51', '515'], dtype=object),
 'sardona': array(['SA1.1'], dtype=object),
 'schwarzbach': array(['212', '112', '118', '217', '218', '314', '215', '12', '05', '06',
        '114', '115', '116', '117', 'Akk3', 's14', 's23', 's25', 's28',
        's4', 's66', 's7', 's9', 'Akk1', 's5', 's60', '16', '27'],
       dtype=object),
 'schwarzberg': array(['SIII', '120', '123', 'SII', 'SIV', 'SXXIII', 'SV', 'SXXI', '124',
        '121', '19123', '19124', '20120', '20123', '20124', '21120',
        '21123', '21124', '19120', '22124', '22124b', '22120', '22123'],
       dtype=object),
 'segnes': array(['Se1.1', 'Se2.1', 'Se1.2'], dtype=object),
 'sexrouge': array(['2', '4', '6', '5', '3', '7', '16', '23', '29', '02', '1', '10',
        '30', '788', 's-09', 's-20', '14', '17', '19', 'ser4-23',
        'ser6-23', 'serTK-22', 's-22', 's139', 's140', 's162', 's210',
        's27', 's45', 'ser2-22b'], dtype=object),
 'silvretta': array(['2', '5', '6', '7', '4', '8', '11', '3', '10', '12', '13', '14',
        '15', 'R', 'S', 'Q', 'E', 'J', 'L', 'M', 'N', 'O', 'D', 'F', 'X',
        'W', 'B', 'V', 'I', '2900', 'BU', '9', 'H', 'C', 'Kn', 'A', 'Y',
        'Gn', 'SLF', 'P', '1', 'IV', 'III', 'Ga', 'II', 'Ka', 'B000', '06',
        '05', '0310', '02', '01', '08', '03', '1110', '04', '17', '1205',
        '1216', '1218', '07', '007', 'B058', '0702', '0610', '0611',
        '0905', '0818', '091', '1104', '1111', '1312', '1317', '1306',
        '16', '1617', '1903', '1910', '1901', '18', '1917', 'A098', '015',
        'B085', 'B046', 'B070', 'A006', '1115', '1117', '100', '0907',

In [50]:
# Get stakes per elevation bands:
N_bands = 10
df_aletsch = df_pm[df_pm.GLACIER == 'aletsch']
df_aletsch['EL_BIN'] = pd.cut(df_aletsch.POINT_ELEVATION, N_bands, precision=0, labels = [f'EL_{i}' for i in range(N_bands)])
df_aletsch

# save aletsch coordinates
df_aletsch[['GLACIER', 'POINT_ID', 'POINT_LAT', 'POINT_LON',
              'PERIOD', 'YEAR', 'EL_BIN']].to_csv(path_PMB_GLAMOS_csv + 'coordinates_aletsch.csv')